name: Docker Image CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend Jar
        working-directory: MtdrSpring/backend
        run: mvn clean package spring-boot:repackage
      - name: Build Docker Image
        working-directory: MtdrSpring/backend
        run: docker build -f Dockerfile -t my-image-name:$(date +%s) .