name: "Build with Nix"
on:
  push:
    branches:
      - nix

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 435vic/todoapp

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image with Nix and load into Docker
        run: |
          nix run .#docker | docker image load
          docker image tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest 
      - name: Push image to registry
        run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

